name: "test"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
    tags:
      - "*"

jobs:
  test-auto:
    name: "Test"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - name: Run
        run: |
          printf 'GITHUB_EVENT_NAME: %s\n' "${GITHUB_EVENT_NAME}"
          printf 'GITHUB_SHA: %s\n' "${GITHUB_SHA}"
          printf 'GITHUB_REF: %s\n' "${GITHUB_REF}"
